### ISSUE TITLE
遅くないwebサイトを作る方法

### ISSUE THREAD

**Issue by ncaq** [ncaq/www.ncaq.net#78]
`<script>`を`<body>`の最後に書けというだけの話

**Comment by Petitsurume** [comment]
`<script>`に`defer`付けると同等になるはず

**Comment by ncaq** [comment]
`defer`はサポートされてないこともあるしそういう用途なら`async`の方が良い
`defer`は実行順序を規定したい時に書きたい(だがサポートされてないことがあり死)

**Comment by Petitsurume** [comment]
なるほどね

**Comment by Petitsurume** [comment]
最新ブラウザーを使ってるやつ以外サポートしないアレで行くと普通に使えそうhttps://caniuse.com/#feat=script-defer

**Comment by ncaq** [comment]
最新ブラウザだけサポートすることを考えても
速度面だけ考えると`async`付けるだけで良い

**Comment by Petitsurume** [comment]
まあせやな
